# Generated by Django 3.1.7 on 2021-04-09 00:07

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrendItemModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('asx_code', models.TextField()),
                ('type', models.CharField(choices=[('REVENUE', 'REVENUE'), ('EXPENSES', 'EXPENSES'), ('EPS', 'EPS')], max_length=10)),
                ('year', models.IntegerField()),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrendsModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('asx_code', models.TextField()),
                ('eps_trend', models.ManyToManyField(related_name='eps', to='trends.TrendItemModel')),
                ('expenses_trend', models.ManyToManyField(related_name='expenses', to='trends.TrendItemModel')),
                ('revenue_trend', models.ManyToManyField(related_name='revenue', to='trends.TrendItemModel')),
            ],
        ),
    ]
