# Generated by Django 3.1.7 on 2021-06-28 09:18

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('asx_code', models.TextField()),
                ('date', models.TextField()),
                ('close', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StockPriceModel',
            fields=[
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('asx_code', models.TextField()),
                ('stock_prices', models.ManyToManyField(to='stock_prices.PriceModel')),
            ],
        ),
    ]
