# Generated by Django 3.1.7 on 2021-06-01 05:08

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsxCompanyModel',
            fields=[
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('asx_code', models.CharField(max_length=3)),
                ('parent_sector', models.CharField(max_length=100)),
                ('sector', models.CharField(choices=[('Energy', 'Energy'), ('Banks', 'Banks'), ('Materials', 'Materials'), ('Capital Goods', 'Capital Goods'), ('Retailing', 'Retailing'), ('Food, Beverage & Tobacco', 'Food, Beverage & Tobacco'), ('Food & Staples Retailing', 'Food & Staples Retailing'), ('Real Estate', 'Real Estate'), ('Class Pend', 'Class Pend'), ('Media & Entertainment', 'Media & Entertainment'), ('Consumer Durables & Apparel', 'Consumer Durables & Apparel'), ('Household & Personal Products', 'Household & Personal Products'), ('Pharmaceuticals, Biotechnology & Life Sciences', 'Pharmaceuticals, Biotechnology & Life Sciences'), ('Utilities', 'Utilities'), ('Automobiles & Components', 'Automobiles & Components'), ('Transportation', 'Transportation'), ('Technology Hardware & Equipment', 'Technology Hardware & Equipment'), ('Diversified Financials', 'Diversified Financials'), ('Insurance', 'Insurance'), ('Consumer Services', 'Consumer Services'), ('Commercial & Professional Services', 'Commercial & Professional Services'), ('Software & Services', 'Software & Services'), ('Telecommunication Services', 'Telecommunication Services'), ('Health Care Equipment & Services', 'Health Care Equipment & Services'), ('Semiconductors & Semiconductor Equipment', 'Semiconductors & Semiconductor Equipment'), ('Not Applic', 'Not Applic')], max_length=100)),
            ],
        ),
    ]
